export const LEDGER_ACCOUNT_CODES = {
  CASH_MPESA_PAYBILL: "1000",
  CLEARING_MPESA_PENDING: "1100",
  LIABILITY_CREATORS_PAYABLE: "2000",
  LIABILITY_VAT_OUTPUT: "2100",
  LIABILITY_WITHHOLDING: "2200",
  REVENUE_PLATFORM_COMMISSION: "4000",
  EXPENSE_PAYMENT_PROCESSING: "5000",
  EXPENSE_PAYOUT_FEES: "5100",
  EQUITY_RETAINED_EARNINGS: "3000"
} as const;

export const DEFAULT_PLATFORM_COMMISSION_PERCENT = 30;
export const DEFAULT_VAT_RATE = 0.16;
export const DEFAULT_LEDGER_CURRENCY = "KES";

export const DONATION_SUCCESS_EVENT = "donation.success";
export const PAYOUT_DISBURSED_EVENT = "payout.disbursed";
